# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'IdleMe' do

pod 'Alamofire', '~> 1.2'
pod 'SwiftyJSON', '~> 2.2.0'

end

target 'IdleMeTests' do

pod 'Alamofire', '~> 1.2'
pod 'SwiftyJSON', '~> 2.2.0'

end

