#Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'IdleMee' do

platform :ios, '8.0'
use_frameworks!

pod 'SwiftyJSON', '~> 2.2.0'
pod 'Alamofire', '~> 1.2'

end

target 'IdleMeeTests' do

end

