# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'


source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'BiologicalClock' do

pod 'Alamofire', '~> 1.2'

end

target 'BiologicalClockTests' do

pod 'Alamofire', '~> 1.2'

end

